# Generated by Django 2.1.1 on 2019-03-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGE', models.IntegerField(default=0)),
                ('HEIGHT', models.IntegerField(default=0)),
                ('datetime', models.DateField(default=0)),
                ('WEIGHT', models.FloatField(default=0)),
                ('FATPER', models.FloatField(default=0)),
                ('FATAMT', models.FloatField(default=0)),
                ('FFMAMT', models.FloatField(default=0)),
                ('MSLAMT', models.FloatField(default=0)),
                ('BMI', models.FloatField(default=0)),
                ('Muscle_Index', models.FloatField(default=0)),
            ],
        ),
    ]
